packages:
  user-management:
    name: "user management"
    version: "0.1.0"
    gitUrl: "https://github.com/shaple/user-management"
    shortDescription: "User Management VAPI"
    longDescription: "This is a VAPI for managing membership information."
    access: "private"
  matching-management:
    name: "matching management"
    version: "1.1.0"
    gitUrl: "https://github.com/shaple/matching-management"
    shortDescription: "Matching Management VAPI"
    longDescription: "This is a VAPI for managing matching between users."
    access: "private"
    dependencies:
      user-management:
        version: "0.1.0"
  follow-management:
    name: "follow management"
    version: "1.0.0"
    gitUrl: "https://github.com/shaple/follow-management"
    shortDescription: "Follow Management VAPI"
    longDescription: "This is a VAPI for creating and managing a user's follow list."
    access: "private"
    dependencies:
      user-management:
        version: "0.1.0"
  feed-management:
    name: "feed management"
    version: "1.2.0"
    gitUrl: "https://github.com/shaple/feed-management"
    shortDescription: "Feed Management VAPI"
    longDescription: "This is a VAPI for creating and managing feeds."
    access: "private"
    dependencies:
      user-management:
        version: "0.1.0"
