services:
  follow-management:
    build: ./follow-management/_core
    volumes:
      - type: bind
        source: ./follow-management
        target: /follow-management
    ports:
      - '8000:9000'
    environment:
      - VAPI_NAME=follow-management
    env_file:
      - .env.dev
  user-management:
    build: ./user-management/_core
    volumes:
      - type: bind
        source: ./user-management
        target: /user-management
    ports:
      - '8001:9000'
    environment:
      - VAPI_NAME=user-management
    env_file:
      - .env.dev
  matching-management:
    build: ./matching-management/_core
    volumes:
      - type: bind
        source: ./matching-management
        target: /matching-management
    ports:
      - '8002:9000'
    environment:
      - VAPI_NAME=matching-management
    env_file:
      - .env.dev