openapi: 3.0.0
info:
  title: Feed Management
  description: |
    VAPI for managing feeds including creating, updating, deleting, and retrieving feed information.
  version: "1.0.0"

paths:
  /get-feed-info:
    get:
      summary: Retrieve information about a specific feed
      parameters:
        - in: query
          name: feed_id
          schema:
            type: string
          required: true
          description: The ID of the feed to retrieve
      responses:
        '200':
          description: Successfully retrieved feed information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Feed'
        '400':
              description: Missing feed-id
        '405':
              description: Method not allowed

  /get-feed-list:
    get:
      summary: Retrieve a list of feeds
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: page_size
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: Successfully retrieved the list of feeds
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Feed'
                  page:
                    type: integer
                  pageSize:
                    type: integer

  /post-feed:
    post:
      summary: Create a new feed
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
            description: Bearer token required to authorize the request
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                media_file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successfully created a new feed
        '400':
          description: Missing title or description
        '401':
          description: Unauthorized
        '405':
          description: Method not allowed

  /update-feed:
    patch:
      summary: Update an existing feed
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
            description: Bearer token required to authorize the request
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                feed_id:
                  type: string
                title:
                  type: string
                description:
                  type: string
                media_file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successfully updated the feed
        '400':
          description: Missing required fields
        '401':
          description: Unauthorized
        '405':
          description: Method not allowed

  /delete-feed:
    delete:
      summary: Delete a feed
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
            description: Bearer token required to authorize the request
        - in: query
          name: feed_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully deleted the feed
        '400':
          description: Missing feed-id
        '401':
          description: Unauthorized
        '405':
          description: Method not allowed

components:
  schemas:
    Feed:
      type: object
      properties:
        id:
          type: string
        user_id:
          type: string
        title:
          type: string
        description:
          type: string
        feed_media:
          type: string
        created_at:
          type: string
          format: date-time
        deleted_at:
          type: string
          format: date-time
