openapi: 3.0.0
info:
  title: User Management
  description: |
    VAPI for managing users. Provides the ability to view, edit, and unsubscribe users. 
    This VAPI depends on the 'Auth BaseAPI'
  version: "1.0.0"

paths:
  /get-user-info:
    get:
      summary: Retrieve user information
      parameters:
        - in: query
          name: user_id
          schema:
            type: string
          required: true
          description: The ID of the user to retrieve
      responses:
        '200':
          description: User information retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
        '400':
          description: Missing user-id
        '405':
          description: Method not allowed

  /delete-user:
    delete:
      summary: Delete a user
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
          description: Bearer token required to authorize the request
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              should_soft_delete:
                type: boolean
      responses:
        '200':
          description: Request processed successfully
        '400':
          description: Missing should_soft_delete
        '401':
          description: Unauthorized
        '405':
          description: Method not allowed

  /update-user:
    patch:
      summary: Update user 
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
          description: Bearer token required to authorize the request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserRequest'
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
        '400':
          description: No data to update
        '401':
          description: Unauthorized
        '405':
          description: Method not allowed

components:
  schemas:
    UserInfo:
      type: object
      properties:
        user_name:
          type: string
        full_name:
          type: string
        avatar_url:
          type: string
        email:
          type: string
        phone:
          type: string

    UpdateUserRequest:
      type: object
      properties:
        email:
          type: string
        phone:
          type: string
        password:
          type: string
        user_name:
          type: string
        full_name:
          type: string
        avatar_url:
          type: string
